/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projebp2;

import java.awt.Color;
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class AnaSayfa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnaSayfa.class.getName());

   
    private double enYuksekSkor;
    private String KullaniciAdi;
    long startTime;
    private String eposta;
    public ArrayList<ColorBox> boxes=new ArrayList<>();
    Color[] renkler = {Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW, 
                   Color.ORANGE, Color.PINK, Color.CYAN, Color.MAGENTA, 
                   Color.WHITE, Color.GRAY};
    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa(String KullaniciAd,double EnYuksekskor,String Eposta) {
        initComponents();
        OyunPanel.setLayout(null);
        this.KullaniciAdi=KullaniciAd;
        this.eposta=Eposta;
        this.enYuksekSkor=EnYuksekskor;
        NameLabel.setText("Kullanici:" + KullaniciAd);
        SkorLabel.setText("En son girilen Skor:" + enYuksekSkor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Spinner = new javax.swing.JSpinner();
        LeftButton = new javax.swing.JButton();
        UpButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        DownButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        SkorLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        OyunPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        Spinner.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        LeftButton.setText("Left");
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        UpButton.setText("UP");
        UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButtonActionPerformed(evt);
            }
        });

        RightButton.setText("Right");
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        DownButton.setText("Down");
        DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButtonActionPerformed(evt);
            }
        });

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        SkorLabel.setForeground(new java.awt.Color(0, 0, 0));

        NameLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(LeftButton)
                        .addGap(55, 55, 55)
                        .addComponent(RightButton)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(DownButton)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(UpButton)
                                .addGap(94, 94, 94)))
                        .addComponent(SkorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SkorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LeftButton)
                            .addComponent(RightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DownButton)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        OyunPanel.setBackground(new java.awt.Color(153, 255, 204));
        OyunPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        OyunPanel.setLayout(null);
        getContentPane().add(OyunPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        
        startTime=System.currentTimeMillis();
        for (ColorBox box : boxes) {
            OyunPanel.remove(box);
        }
        boxes.clear();
        
        int SpinnerSayi=(int) Spinner.getValue();
        
        for (int i = 0; i < SpinnerSayi; i++) {
            Color renk=renkler[i];
            
            for (int j = 0; j <2; j++) {
                int RandomX=(int)(Math.random()*(600-200));
                int RandomY=(int)(Math.random()*(400-200));
                
                ColorBox box=new ColorBox(RandomX,RandomY,50,50, renk,this);
                boxes.add(box);
                OyunPanel.add(box);
            }
            OyunPanel.revalidate();
            OyunPanel.repaint();
        }
        
    }//GEN-LAST:event_StartButtonActionPerformed

    
    private void UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButtonActionPerformed
        int Pixel=20;
        for (ColorBox box : boxes) {
            if(box.Odakli()){
                int YeniY=box.getY()-Pixel;
                 if(YeniY<0){
                 YeniY=0;}
                 box.setLocation(box.getX(),YeniY);
            }}
       Carpisma();
    }//GEN-LAST:event_UpButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        int Pixel=20;
        for (ColorBox box: boxes) {
            if(box.Odakli()){
                int YeniX=box.getX()-Pixel;
                if(YeniX<0){
                    YeniX=0;}
                box.setLocation(YeniX,box.getY());
            }
        }
        Carpisma();
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        int Pixel=20;
        for (ColorBox box: boxes) {
            if(box.Odakli()){
                int YeniX=box.getX()+Pixel;
                if(YeniX>OyunPanel.getWidth()-box.getWidth()){
                    YeniX=OyunPanel.getWidth()-box.getWidth();}
                box.setLocation(YeniX, box.getY());
            }
        }
        Carpisma();
    }//GEN-LAST:event_RightButtonActionPerformed
     
    private void SkorKaydet(double YeniSkor){
        try{
        File file=new File("users.txt");
        BufferedReader reader = new BufferedReader(new FileReader(file));
        StringBuilder sb = new StringBuilder();
        String line;
        
        while((line=reader.readLine())!=null){
            String[] parca=line.split(";");
            if(parca[0].equalsIgnoreCase(eposta)){
                line=parca[0] + ";" + parca[1] + ";" + parca[2] + ";" + parca[3] + ";" + YeniSkor;
            }
            sb.append(line).append("\n");
        }
        reader.close();
        
        BufferedWriter writer=new BufferedWriter(new FileWriter(file));
        writer.write(sb.toString());
        writer.close();
        }
        catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Dosya hatası: " + e.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    }
    }
    private void Carpisma(){
         ColorBox Kutu1=null;
         ColorBox Kutu2=null;
         
         for (int i = 0; i <boxes.size(); i++) {
             for (int j =i+1; j < boxes.size(); j++) {
                 ColorBox box1=boxes.get(i);
                 ColorBox box2=boxes.get(j);
                 
                 Rectangle r1=box1.getBounds();
                 Rectangle r2=box2.getBounds();
                 
                 if(r1.intersects(r2) && box1.GetRenk().equals(box2.GetRenk())){
                     Kutu1=box1;
                     Kutu2=box2;
                     break;
                 }
             }
         }
         if(Kutu1!=null && Kutu2!=null){
             OyunPanel.remove(Kutu1);
             OyunPanel.remove(Kutu2);
             boxes.remove(Kutu1);
             boxes.remove(Kutu2);
             OyunPanel.revalidate();
             OyunPanel.repaint();
         }
         if(boxes.isEmpty()){
             long EndTime=System.currentTimeMillis();
             double seconds=(EndTime-startTime)/1000.0;
             
             int sayi=(int) Spinner.getValue();
             double normalizedScore= seconds * (5.0/sayi);
             String skor=String.format("%.1f",normalizedScore);
             
            if(enYuksekSkor == 0.0){
    enYuksekSkor = normalizedScore;
    SkorLabel.setText("En son girilen Skor:" + String.format("%.1f", enYuksekSkor));
    SkorKaydet(enYuksekSkor);
    JOptionPane.showMessageDialog(null,"Oyun Bitti!\n" +
        "Kullanıcı: " + KullaniciAdi + "\n" +
        "Süre: " + String.format("%.1f", seconds) + " saniye\n" +
        "Skor: " + skor + "\n" +
        "İlk skorunuz kaydedildi!");
} else if(normalizedScore < enYuksekSkor){
    enYuksekSkor = normalizedScore;
    SkorLabel.setText("En son girilen Skor:" + String.format("%.1f", enYuksekSkor));
    SkorKaydet(enYuksekSkor);
    JOptionPane.showMessageDialog(null,"Oyun Bitti!\n" +
        "Kullanıcı: " + KullaniciAdi + "\n" +
        "Süre: " + String.format("%.1f", seconds) + " saniye\n" +
        "Skor: " + skor + "\n" +
        "Tebrikler! Yeni rekor: " + String.format("%.1f", enYuksekSkor));
} else {
    JOptionPane.showMessageDialog(null,"Oyun Bitti!\n" +
        "Kullanıcı: " + KullaniciAdi + "\n" +
        "Süre: " + String.format("%.1f", seconds) + " saniye\n" +
        "Skor: " + skor + "\n" +
        "Maalesef rekoru geçemediniz!\n" +
        "Mevcut Rekor: " + String.format("%.1f", enYuksekSkor));
}
         }
         
     }
    private void DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButtonActionPerformed
        int Pixel=20;
        for (ColorBox box : boxes) {
        if (box.Odakli()) {
            int yeniY = box.getY() + Pixel;
            if (yeniY > OyunPanel.getHeight()- box.getHeight()) 
                yeniY = OyunPanel.getHeight() - box.getHeight();
            box.setLocation(box.getX(), yeniY);
        }
    }
        Carpisma();
    }//GEN-LAST:event_DownButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnaSayfa("",0.0,"").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownButton;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel OyunPanel;
    private javax.swing.JButton RightButton;
    private javax.swing.JLabel SkorLabel;
    private javax.swing.JSpinner Spinner;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton UpButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
