/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projebp2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.out;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class User extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User.class.getName());

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        KayitOlButton = new javax.swing.JButton();
        AdTextField = new javax.swing.JTextField();
        EPostaTextField = new javax.swing.JTextField();
        SifreTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SoyadTextField = new javax.swing.JTextField();
        TekrarSifreTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EPostatextField = new javax.swing.JTextField();
        SifreTexrfield = new javax.swing.JTextField();
        GirisYapButton = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(400, 420));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 450));

        KayitOlButton.setText("Kayit Ol");
        KayitOlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KayitOlButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ad:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("E-Posta:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sifre:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Soyad:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tekrardan sifre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KayitOlButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPostaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SifreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(TekrarSifreTextField))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EPostaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TekrarSifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addComponent(KayitOlButton)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Kayit Ol", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 430));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("E-Posta:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Sifre:");

        GirisYapButton.setText("Giris yap");
        GirisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisYapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EPostatextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SifreTexrfield, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(GirisYapButton)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EPostatextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SifreTexrfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(GirisYapButton)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Giris Yap", jPanel2);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KayitOlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KayitOlButtonActionPerformed
       String Ad=AdTextField.getText().trim();
       String Soyad=SoyadTextField.getText().trim();
       String EPosta=EPostaTextField.getText().trim();
       String Sifre=SifreTextField.getText().trim();
       String TekrarSifre=TekrarSifreTextField.getText().trim();
       if(Ad.isEmpty()|| Soyad.isEmpty()||EPosta.isEmpty()|| Sifre.isEmpty() || TekrarSifre.isEmpty()){
           JOptionPane.showMessageDialog(null, "verilen alanlaridan birini bos biraktiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
           return;
       }
       Pattern pattern=Pattern.compile("^(?=.*[A-Z])(?=.*[0-9]).{6,}$",Pattern.CASE_INSENSITIVE);
       Matcher match=pattern.matcher(Sifre);
       boolean MatchFound=match.find();
       if(!MatchFound){
           JOptionPane.showMessageDialog(rootPane, "girilen sifre 6 karakter bulundurmali \n en az bir buyuk harf \n bir rakam bulundurmalidir!",
                   "Hata!",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(!Sifre.equals(TekrarSifre)){
           JOptionPane.showMessageDialog(rootPane,"Sifrede Hata Olustu!", "Hata!",JOptionPane.ERROR_MESSAGE);
           return;
       }
       Pattern PAttern=Pattern.compile("^[\\w.%+-]+@[a-zA-z0-9.-]+\\.[a-z]{2,}$");
       Matcher mAtch=PAttern.matcher(EPosta);
       boolean Matchfound=mAtch.find();
       if(!Matchfound){
           JOptionPane.showMessageDialog(null, "EPosta gecersiz!","Hata!",JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       try{
           File file=new File("users.txt");
           
           if(file.exists()){
               BufferedReader read=new BufferedReader(new FileReader(file));
               String line;
                while ((line = read.readLine()) != null){
                   String[] piece=line.split(";");
               if(piece.length>=1 && piece[0].equals(EPosta)){
                   JOptionPane.showMessageDialog(null, "bu E-Posta zaten kayitli!", "Hata!",JOptionPane.ERROR_MESSAGE);
               read.close();
               return;
               }
                }
                read.close();}
           
           BufferedWriter Write=new BufferedWriter(new FileWriter(file,true));
           Write.write(EPosta + ";" + Ad + ";" + Soyad + ";" + Sifre + ";0.0");
            Write.newLine();
            Write.close();
            JOptionPane.showMessageDialog(null, "Kayıt başarılı!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

        
        AdTextField.setText("");
        SoyadTextField.setText("");
        EPostaTextField.setText("");
        SifreTextField.setText("");
        TekrarSifreTextField.setText("");
       }
       catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Dosya hatası: " + e.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_KayitOlButtonActionPerformed

    private void GirisYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisYapButtonActionPerformed
        String EPosta=EPostatextField.getText().trim();
        String Sifre=SifreTexrfield.getText().trim();
        
        if(EPosta.isEmpty()|| Sifre.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "verilen alanlaridan birini bos biraktiniz! ", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
           File file=new File("users.txt");
           if(!file.exists()){
               JOptionPane.showMessageDialog(rootPane, "Kayitli Kullanici Bulunamadi!\n tekrar deneyiniz", "Hata!", JOptionPane.WARNING_MESSAGE);
               return;
           }
           BufferedReader read=new BufferedReader(new FileReader(file));
           String line;
           boolean bulundu=false;
          while((line=read.readLine())!=null){
              String[] parca=line.split(";");
           if(parca.length>=4 && parca[0].equalsIgnoreCase(EPosta) && parca[3].equals(Sifre)){
                  bulundu=true;
                  read.close();
                  JOptionPane.showMessageDialog(rootPane, "Giris Basarili",null, JOptionPane.INFORMATION_MESSAGE);

                  EPostatextField.setText("");
                  SifreTexrfield.setText("");
                   
                  this.dispose();
                  AnaSayfa anasayfa=new AnaSayfa(parca[1],Double.parseDouble(parca[4]),parca[0]);
                 anasayfa.setVisible(true);
                  
           break;   
           }}
          if(!bulundu){
              read.close();
              JOptionPane.showMessageDialog(rootPane, "Giris Basarisiz!", "Hata", JOptionPane.WARNING_MESSAGE);
              
          }

        }
        catch(IOException e){
        JOptionPane.showMessageDialog(rootPane,"Dosya Hatasi", "Hata!:" +e.getMessage() , JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_GirisYapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdTextField;
    private javax.swing.JTextField EPostaTextField;
    private javax.swing.JTextField EPostatextField;
    private javax.swing.JButton GirisYapButton;
    private javax.swing.JButton KayitOlButton;
    private javax.swing.JTextField SifreTexrfield;
    private javax.swing.JTextField SifreTextField;
    private javax.swing.JTextField SoyadTextField;
    private javax.swing.JTextField TekrarSifreTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
